# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "duduta-terraform-local-development"
    encrypt = true
    key     = "vm-template/terraform.tfstate"
    profile = "duduta"
    region  = "eu-west-1"
  }
}
